name: Emacs 30

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "Formula/emacs-mac-exp@30.rb"
      - "patches/**"
      - "Library/**"
      - ".github/workflows/emacs30.yaml"
  pull_request:
    paths:
      - "Formula/emacs-mac-exp@30.rb"
      - "patches/**"
      - "Library/**"
      - ".github/workflows/emacs30.yaml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
        build_opts:
          - ""
          - "--with-transparent-titlebar"
          - "--with-starter"
          - "--with-optimization-flags"
          - "--debug-symbols --build-from-source"
          - "--with-arc"
          - "--with-mac-metal"
          - "--cc llvm_clang"
          - "--without-native-compilation"
    env:
      HOMEBREW_EMACS_MAC_MODE: local
    steps:
      - uses: actions/checkout@v4

      - name: Get cache keys
        id: get-cache-keys
        run: |
          echo EMACS_KEY=$(git ls-remote https://github.com/jdtsmith/emacs-mac.git refs/heads/emacs-mac-30_1_exp |  sed -e 's| *refs/heads/emacs-mac-30_1_exp||') >> "$GITHUB_OUTPUT"
          echo HOMEBREW_KEY=$(echo $(brew info --json gcc llvm $(brew missing ./Formula/emacs-mac-exp@30.rb) | jq -c '.[] | ({name:.name, version:.versions.stable})') | sort | sha256) >> "$GITHUB_OUTPUT"
          {
            echo 'HOMEBREW_PATHS<<EOF'
            for dep in gcc $(brew missing ./Formula/emacs-mac-exp@30.rb); do
                echo "~/Library/Caches/Homebrew/${dep}-*"
                echo "~/Library/Caches/Homebrew/downloads/*--${dep}-*"
            done
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Emacs Cache
        uses: actions/cache@v4
        with:
          key: emacs-${{ steps.get-cache-keys.outputs.EMACS_KEY }}
          path: |
            ~/Library/Caches/Homebrew/emacs-mac-exp@30--git

      - name: Homebrew Cache
        uses: actions/cache@v4
        if: ${{ steps.get-cache-keys.outputs.HOMEBREW_PATHS }}
        with:
          key: homebrew-${{matrix.os}}-${{ steps.get-cache-keys.outputs.HOMEBREW_KEY }}
          path: |
            ${{ steps.get-cache-keys.outputs.HOMEBREW_PATHS }}

      - name: Install LLVM
        run: brew install llvm

      - name: Build Emacs
        run: |
          tap=$(brew --prefix)/Library/Taps/pkryger/homebrew-emacsmacport-exp
          mkdir -p "$(dirname "${tap}")"
          ln -s "${GITHUB_WORKSPACE}" "${tap}"
          brew install pkryger/emacsmacport-exp/emacs-mac-exp@30 --HEAD ${{ matrix.build_opts }} --verbose
          rm "${tap}"

      - name: Test Building
        run: "\"$(brew --prefix)/bin/emacs\" --batch --eval='(print (+ 2 2))'"

      - name: Pack up build logs
        if: ${{ always() }}
        run: |
          BUILD_OPTS=$(echo "${{ matrix.build_opts }}" | sed 's/ //')
          echo "build_opts=$BUILD_OPTS" >> "$GITHUB_ENV"
          RUNNER_OS=$(echo "${{ matrix.os }}" | sed 's/ //')
          echo "runner_os=$RUNNER_OS" >> "$GITHUB_ENV"
          tar -C ~/Library/Logs/Homebrew/emacs-mac-exp@30/ -czvf ~/Library/Logs/Homebrew/emacs-mac-exp@30-${RUNNER_OS}${BUILD_OPTS}.tar.gz .

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: emacs-mac-exp@30-${{ env.runner_os }}${{ env.build_opts }}.tar.gz
          path: |
            ~/Library/Logs/Homebrew/emacs-mac@30-${{ env.runner_os }}${{ env.build_opts }}.tar.gz
